---
- name: Download esl-erlang package.
  get_url:
    url: "{{ esl_erlang_rpm_url }}"
    dest: "/tmp/{{ esl_erlang_rpm }}"

- name: Ensure esl-erlang is installed.
  yum:
    name: "/tmp/{{ esl_erlang_rpm }}"
    state: "present"

- name: Add packagecloud GPG key.
  rpm_key:
    key: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    state: present

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
